[workspace]
resolver = "2"
members = [
  "check_api_superset",
  "generate_api",
]

[workspace.package]
authors = ["Microsoft"]
edition = "2021"
license = "MIT"
repository = "https://github.com/Azure/azure-sdk-for-rust"
rust-version = "1.95"

[workspace.dependencies]
clap = { version = "4.5.58", features = ["derive"] }
rustdoc-types = "0.57.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
toml = "0.8.20"
