[package]
name = "azure_storage_stress_blob"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
azure_core = { path = "../../core/azure_core", version = "1.2.0-beta.1", features = ["xml"] }
azure_core_test = { path = "../../core/azure_core_test", features = ["tracing"] }
azure_identity.path = "../../identity/azure_identity"
azure_storage_blob.path = "../azure_storage_blob"
azure_storage_stress.path = "../azure_storage_stress"
bytes.workspace = true
clap = { workspace = true, features = ["derive"] }
crc-fast = "1.9.0"
env_logger = "0.11.10"
futures.workspace = true
log = "0.4.29"
rand.workspace = true
reqwest = { workspace = true, features = ["rustls"] }
tokio = { workspace = true, features = ["rt"] }
uuid.workspace = true

[lints]
workspace = true
