# Manually-triggered pipeline to pull crates from upstream into feed.

trigger: none
pr: none

extends:
  template: /eng/pipelines/templates/stages/1es-redirect.yml
  parameters:
    stages:
    - stage: Fetch
      variables:
      - template: /eng/pipelines/templates/variables/image.yml
      - template: /eng/pipelines/templates/variables/rust.yml
      jobs:
      - template: /eng/common/pipelines/templates/jobs/generate-job-matrix.yml
        parameters:
          JobTemplatePath: /eng/pipelines/templates/jobs/fetch.yml
          MatrixConfigs:
          - Name: rust_fetch
            Path: /eng/pipelines/templates/stages/platform-matrix.json
            Selection: all
            GenerateVMJobs: true
          CloudConfig:
            Cloud: public
          SparseCheckoutPaths:
          - /*
