trigger: none

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: auto
    IncludeRelease: false
    RunLiveTests: false
    MatrixConfigs:
      - Name: rust_pr_test_base
        Path: eng/pipelines/templates/stages/pr-platform-matrix.json
        Selection: all
        GenerateVMJobs: true
